config/routes.rb
Rails.application.routes.draw do

  get 'admin', to: 'static#index'

  get 'hotspot_customer', to: 'hotspot_customer#index'
  get '/hotspot_customer/show_log', to: 'hotspot_customer#show_log'

  get 'hotspot_customer/new'

  get 'hotspot_customer/create'

  get 'hotspot_customer/show'

  get 'hotspot_customer/update'

  get 'hotspot_customer/edit'

  get 'router/index'
  get 'router', to: 'router#index'
  get 'router/new'
  post 'router/create'
  get 'router/destroy'

  get '/router/:id', to: 'router#show'
  get '/router/edit/:id', to: 'router#edit'
  patch '/router/edit/:id', to: 'router#update'

  get 'wifi/index'

  get 'wifi/login'
  post 'wifi/login', to: 'wifi#login_post'

  get 'wifi/logout'

  get 'wifi/registration'
  post 'wifi/registration', to: 'wifi#registration_post'

  get 'wifi/agreement'
  get 'wifi/check'

  root 'wifi#agreement'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/router.rb
class Router < ApplicationRecord
  validates :identity, presence: true, uniqueness: true
  validates :ip, presence: true, uniqueness: true, :format => {
      :with => Regexp.union(Resolv::IPv4::Regex, Resolv::IPv6::Regex)
  }
  validates :port, presence: true
  validates :login, presence: true
  validates :password, presence: true


end

app/controllers/router_controller.rb
class RouterController < ApplicationController
  before_action :permit_params
  before_action :require_admin
  before_action :set_router, only: [:show, :update, :edit]
  def index
    @routers = Router.all
  end

  def new
    @router = Router.new
  end

  def create
    @router = Router.new params[:router]
    if @router.valid?
      @router.save!
      flash[:success] = "Роутер #{@router.identity} добавлен"
      redirect_to router_index_url
    else
      render action: :new
    end
  end

  def update
    if @router.update_attributes(params[:router])
      flash[:success] = "Роутер #{@router.identity} обновлен"
      redirect_to "/router/#{@router.id}"
    else
      render action: :edit
    end
  end

  def destroy
  end


  def show

  end

  def edit

  end

  def permit_params
    params.permit!
  end

  def set_router
    @router = Router.find(params[:id])
  end
end

app/helpers/router_helper.rb
module RouterHelper
end

app/views/router/create.html.erb
<h1>Router#create</h1>
<p>Find me in app/views/router/create.html.erb</p>

app/views/router/destroy.html.erb
<h1>Router#destroy</h1>
<p>Find me in app/views/router/destroy.html.erb</p>

app/views/router/edit.html.erb
<%provide(:title, "Редактирование роутера")%>
<div class="container">
  <div class="container-fluid">
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="/admin">Административная панель</a></li>
        <li><a href="/router">Роутеры</a></li>
        <li class="active">Редактировать роутер</li>
      </ol>
      <div class="col-md-offset-0 col-md-6">
        <%= form_for( @router , :html => {:class => "form-router", :role => "form"}, url: "/router/edit/#{params[:id]}") do |f| %>
            <h2 class="">Добавить роутер</h2>


            <%= errors_for(@router) %>


            <div class="form-group <%= @router.errors[:identity].present? ? "has-error" : "" %>">
              <%= f.label :identity, 'Уникальный идентификатор', class: "checkbox" %>
              <%= f.text_field :identity, placeholder: "CloudCore1",  :class => 'form-control input-lg'  %>
              <%= errors_for_input @router, :identity %>
            </div>

            <div class="form-group <%= @router.errors[:ip].present? ? "has-error" : "" %>">
              <%= f.label :ip, 'IPv4', class: "checkbox" %>
              <%= f.text_field :ip, placeholder: "192.168.0.1",  :class => 'form-control input-lg'  %>
              <%= errors_for_input @router, :ip %>
            </div>

            <div class="form-group <%= @router.errors[:port].present? ? "has-error" : "" %>">
              <%= f.label :port, 'API PORT', class: "checkbox" %>
              <%= f.text_field :port, placeholder: "8728",  :class => 'form-control input-lg'  %>
              <%= errors_for_input @router, :port %>
            </div>

            <div class="form-group <%= @router.errors[:login].present? ? "has-error" : "" %>">
              <%= f.label :login, 'API Логин', class: "checkbox" %>
              <%= f.text_field :login, placeholder: "api_user",  :class => 'form-control input-lg'  %>
              <%= errors_for_input @router, :login %>
            </div>

            <div class="form-group <%= @router.errors[:password].present? ? "has-error" : "" %>">
              <%= f.label :password, 'API Пароль', class: "checkbox" %>
              <%= f.text_field :password, placeholder: "api_password",  :class => 'form-control input-lg'  %>
              <%= errors_for_input @router, :password %>
            </div>

            <div class="form-group">
              <%= f.submit "Редактировать", :class=> "btn btn-lg btn-primary btn-block" %>
            </div>

            </form>
        <% end %>
      </div>
    </div>

  </div>
</div>



<script>
    jQuery(function($){

        $("#wifi_login_form_phone").mask("7 (999) 999-99-99");
        $("#wifi_login_form_phone").focus();

    });
</script>

app/views/router/index.html.erb
<%provide(:title, "Роутеры")%>
<div class="container">
  <div class="container-fluid">
    <div class="row"> <ol class="breadcrumb">
      <li><a href="/admin">Административная панель</a></li>
      <li class="active">Роутеры</li>
    </ol>
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-10">  <h2 class="magin-0">Роутеры</h2></div>
          <div class="col-md-2"><a class="btn btn-primary pull-right" href="/router/new">Добавить</a> </div>
        </div>
        <hr>

        <table class="table table-striped table-hover table-bordered table-condensed">
          <thead>
          <tr>
            <th>Id</th>
            <th>Название</th>
            <th>IP</th>

            <th>Действие</th>
          </tr>
          </thead>
          <tbody>
          <% @routers.each do |router|%>

          <tr>
            <th scope="row"><%= router.id%></th>
            <td><%= router.identity%></td>
            <td><%= router.ip%></td>

            <td>
              <a href="/router/<%= router.id %>"><span class="glyphicon glyphicon-share"></span></a>
              <a href="/router/edit/<%=router.id %>"><span class="glyphicon glyphicon-edit"></span></a>
              <a href="/router/remove/<%= router.id %>"><span class="glyphicon glyphicon-remove"></span></a>
            </td>

          </tr>

              <%end%>

          </tbody>
        </table>
      </div>
    </div>

  </div>
</div> <!-- /container -->

app/views/router/new.html.erb
<%provide(:title, "Добавить роутер")%>
<div class="container">
<div class="container-fluid">
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="/admin">Административная панель</a></li>
      <li><a href="/router">Роутеры</a></li>
      <li class="active">Добавить роутер</li>
    </ol>
    <div class="col-md-offset-0 col-md-6">
      <%= form_for( @router , :html => {:class => "form-router", :role => "form"}, url: router_create_path) do |f| %>
          <h2 class="">Добавить роутер</h2>


          <%= errors_for(@router) %>


          <div class="form-group <%= @router.errors[:identity].present? ? "has-error" : "" %>">
            <%= f.label :identity, 'Уникальный идентификатор', class: "checkbox" %>
            <%= f.text_field :identity, placeholder: "CloudCore1",  :class => 'form-control input-lg'  %>
            <%= errors_for_input @router, :identity %>
          </div>

          <div class="form-group <%= @router.errors[:ip].present? ? "has-error" : "" %>">
            <%= f.label :ip, 'IPv4', class: "checkbox" %>
            <%= f.text_field :ip, placeholder: "192.168.0.1",  :class => 'form-control input-lg'  %>
            <%= errors_for_input @router, :ip %>
          </div>

          <div class="form-group <%= @router.errors[:port].present? ? "has-error" : "" %>">
            <%= f.label :port, 'API PORT', class: "checkbox" %>
            <%= f.text_field :port, placeholder: "8728",  :class => 'form-control input-lg'  %>
            <%= errors_for_input @router, :port %>
          </div>

          <div class="form-group <%= @router.errors[:login].present? ? "has-error" : "" %>">
            <%= f.label :login, 'API Логин', class: "checkbox" %>
            <%= f.text_field :login, placeholder: "api_user",  :class => 'form-control input-lg'  %>
            <%= errors_for_input @router, :login %>
          </div>

          <div class="form-group <%= @router.errors[:password].present? ? "has-error" : "" %>">
            <%= f.label :password, 'API Пароль', class: "checkbox" %>
            <%= f.text_field :password, placeholder: "api_password",  :class => 'form-control input-lg'  %>
            <%= errors_for_input @router, :password %>
          </div>

          <div class="form-group">
            <%= f.submit "Добавить", :class=> "btn btn-lg btn-primary btn-block" %>
          </div>

          </form>
      <% end %>
    </div>
  </div>

</div>
</div>



<script>
    jQuery(function($){

        $("#wifi_login_form_phone").mask("7 (999) 999-99-99");
        $("#wifi_login_form_phone").focus();

    });
</script>

app/views/router/show.html.erb
<%provide(:title, @router.identity)%>
<div class="container">
  <div class="container-fluid">
    <div class="row"><ol class="breadcrumb">
      <li><a href="/admin">Административная панель</a></li>
      <li><a href="/router">Роутеры</a></li>
      <li class="active"><%= @router.identity%></li>
    </ol>
      <div class="col-md-offset-0 col-md-6">
        <h2 class=""><%= @router.identity%></h2>
        <label class="checkbox">IPv4: <%= @router.ip%></label>
        <label class="checkbox">Port: <%= @router.port%></label>
        <label class="checkbox">Логин: <%= @router.login%></label>
        <label class="checkbox">Пароль: <%= @router.password%></label>
      </div>
    </div>
  </div>

</div>
</div> <!-- /container -->

app/views/router/update.html.erb
<h1>Router#update</h1>
<p>Find me in app/views/router/update.html.erb</p>